"""Run the ToA estimation error experiment and store the empirical CDF data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from config import (
    DEFAULT_PAPER_CHANNEL_MODEL,
    DEFAULT_SEARCH_M1,
    DEFAULT_SEARCH_M2,
    DEFAULT_SEED,
    DEFAULT_SIMULATION_MODE,
    PAPER_DOPPLER_HZ,
    PAPER_ITERATIONS_DETECTION,
    PAPER_ITERATIONS_FALSE_ALARM,
    PAPER_NUM_RX,
    build_search_grid,
    build_run_configuration,
    derive_parameters,
    make_rng,
    paper_coverage_cases,
    result_path,
    run_configuration_matches,
)
from detector import run_detection_experiment, run_false_alarm_experiment
from waveform import build_preamble_reference_bank, design_front_end_filter


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--iterations", type=int, default=PAPER_ITERATIONS_DETECTION)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--m1", type=int, default=DEFAULT_SEARCH_M1)
    parser.add_argument("--m2", type=int, default=DEFAULT_SEARCH_M2)
    parser.add_argument("--num-rx", type=int, default=PAPER_NUM_RX)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--mode", type=str, default=DEFAULT_SIMULATION_MODE, choices=("waveform", "fast"))
    parser.add_argument("--doppler-hz", type=float, default=PAPER_DOPPLER_HZ)
    parser.add_argument("--channel-model", type=str, default=DEFAULT_PAPER_CHANNEL_MODEL)
    parser.add_argument(
        "--threshold-calibration-iterations",
        type=int,
        default=PAPER_ITERATIONS_FALSE_ALARM,
    )
    parser.add_argument(
        "--threshold-evaluation-iterations",
        type=int,
        default=PAPER_ITERATIONS_FALSE_ALARM,
    )
    parser.add_argument(
        "--threshold-json",
        type=str,
        default=None,
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
    )
    return parser.parse_args()


def load_thresholds(path: str | Path) -> dict[int, float]:
    """Load thresholds generated by simulate_false_alarm.py."""
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    return {int(entry["L"]): float(entry["threshold"]) for entry in data["cases"]}


def threshold_file_is_usable(path: Path, args: argparse.Namespace) -> bool:
    """
    Check whether an on-disk threshold file is statistically adequate.
    """
    if not path.exists():
        return False

    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    if data.get("result_kind") != "false_alarm":
        return False

    expected_run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    if not run_configuration_matches(data, expected_run_config):
        return False

    for entry in data.get("cases", []):
        if "calibration_trials" not in entry or "evaluation_trials" not in entry:
            return False
        if int(entry["calibration_trials"]) < args.threshold_calibration_iterations:
            return False
        if int(entry["evaluation_trials"]) < args.threshold_evaluation_iterations:
            return False
    return len(data.get("cases", [])) > 0


def resolve_thresholds(args: argparse.Namespace) -> dict[int, float]:
    """
    Load thresholds from disk, or calibrate them if the file is absent or stale.
    """
    threshold_path = (
        Path(args.threshold_json)
        if args.threshold_json is not None
        else result_path(args.mode, "false_alarm_results.json")
    )
    if threshold_file_is_usable(threshold_path, args):
        return load_thresholds(threshold_path)

    print(
        f"Threshold file missing or insufficient at {threshold_path}; "
        "calibrating thresholds first."
    )
    threshold_rng = make_rng(args.seed + 1)
    run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    output = {
        "result_kind": "false_alarm",
        "mode": args.mode,
        "channel_model": args.channel_model,
        "run_config": run_config,
        "cases": [],
    }
    thresholds = {}

    for case in paper_coverage_cases():
        params = derive_parameters(case.preamble_length)
        search_grid = build_search_grid(params, M1=args.m1, M2=args.m2)
        front_end = design_front_end_filter(params)
        references = build_preamble_reference_bank(
            params=params,
            front_end=front_end,
            hopping_seed=args.seed,
        )
        result = run_false_alarm_experiment(
            params=params,
            references=references,
            search_grid=search_grid,
            snr_db=case.snr_db,
            rng=threshold_rng,
            calibration_trials=args.threshold_calibration_iterations,
            evaluation_trials=args.threshold_evaluation_iterations,
            batch_size=args.batch_size,
            num_rx=args.num_rx,
            mode=args.mode,
            front_end=front_end,
        )
        thresholds[case.preamble_length] = result["threshold"]
        output["cases"].append(
            {
                "L": case.preamble_length,
                "snr_db": case.snr_db,
                "mode": args.mode,
                "channel_model": args.channel_model,
                "threshold": result["threshold"],
                "achieved_pfa": result["achieved_pfa"],
                "target_pfa": result["target_pfa"],
                "calibration_trials": result["calibration_trials"],
                "evaluation_trials": result["evaluation_trials"],
                "calibration_statistics_mean": result["calibration_statistics_mean"],
                "calibration_statistics_std": result["calibration_statistics_std"],
                "evaluation_statistics_mean": result["evaluation_statistics_mean"],
                "evaluation_statistics_std": result["evaluation_statistics_std"],
                "calibration_pfa": result["calibration_pfa"],
                "evaluation_false_alarm_count": result["evaluation_false_alarm_count"],
            }
        )

    threshold_path.parent.mkdir(parents=True, exist_ok=True)
    with open(threshold_path, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)
    print(f"Saved calibrated thresholds to {threshold_path}")
    return thresholds


def main() -> None:
    """Entry point for the ToA CDF simulation."""
    args = parse_args()
    rng = make_rng(args.seed)
    thresholds = resolve_thresholds(args)
    run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    output_path = Path(args.output) if args.output is not None else result_path(
        args.mode,
        "toa_cdf_results.npz",
    )

    arrays = {}
    summaries = {
        "result_kind": "toa_cdf_summary",
        "mode": args.mode,
        "channel_model": args.channel_model,
        "run_config": run_config,
        "cases": [],
    }

    for case in paper_coverage_cases():
        params = derive_parameters(case.preamble_length)
        search_grid = build_search_grid(params, M1=args.m1, M2=args.m2)
        front_end = design_front_end_filter(params)
        references = build_preamble_reference_bank(
            params=params,
            front_end=front_end,
            hopping_seed=args.seed,
        )
        result = run_detection_experiment(
            params=params,
            references=references,
            search_grid=search_grid,
            snr_db=case.snr_db,
            threshold=thresholds[case.preamble_length],
            rng=rng,
            num_trials=args.iterations,
            batch_size=args.batch_size,
            num_rx=args.num_rx,
            channel_model=args.channel_model,
            doppler_hz=args.doppler_hz,
            mode=args.mode,
            front_end=front_end,
            collect_errors=True,
        )
        errors = result["toa_errors_us"]
        arrays[f"errors_L_{case.preamble_length}"] = errors
        summary = {
            "L": case.preamble_length,
            "snr_db": case.snr_db,
            "mode": args.mode,
            "channel_model": args.channel_model,
            "num_detected": int(errors.size),
            "median_abs_error_us": float(np.median(np.abs(errors))) if errors.size else None,
            "p90_abs_error_us": float(np.quantile(np.abs(errors), 0.9)) if errors.size else None,
            "p99_abs_error_us": float(np.quantile(np.abs(errors), 0.99)) if errors.size else None,
            "fraction_within_3us": float(np.mean(np.abs(errors) <= 3.0)) if errors.size else None,
        }
        summaries["cases"].append(summary)

        print(
            f"[ToA CDF] L={case.preamble_length:3d} "
            f"mode={args.mode:8s} "
            f"detected={errors.size:5d} "
            f"median |error|={summary['median_abs_error_us']}"
        )

    arrays["_metadata_json"] = np.asarray(
        json.dumps(
            {
                "result_kind": "toa_cdf_samples",
                "mode": args.mode,
                "channel_model": args.channel_model,
                "run_config": run_config,
            }
        )
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(output_path, **arrays)
    summary_path = output_path.with_name("toa_cdf_summary.json")
    with open(summary_path, "w", encoding="utf-8") as handle:
        json.dump(summaries, handle, indent=2)

    print(f"Saved ToA CDF samples to {output_path}")
    print(f"Saved ToA summary to {summary_path}")


if __name__ == "__main__":
    main()
