"""Run parameter validation, front-end cross-checks, and the detection experiment."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from channel import apply_channel_to_waveform, synthesize_received_symbols_batch
from config import (
    DEFAULT_PAPER_CHANNEL_MODEL,
    DEFAULT_SEARCH_M1,
    DEFAULT_SEARCH_M2,
    DEFAULT_SEED,
    DEFAULT_SIMULATION_MODE,
    PAPER_DOPPLER_HZ,
    PAPER_ITERATIONS_DETECTION,
    PAPER_ITERATIONS_FALSE_ALARM,
    PAPER_NUM_RX,
    build_search_grid,
    build_run_configuration,
    derive_parameters,
    make_rng,
    paper_coverage_cases,
    parameter_summary,
    result_path,
    run_configuration_matches,
)
from detector import run_detection_experiment, run_false_alarm_experiment
from hopping import example_sequence_string, validate_hopping_sequence
from receiver import (
    compare_search_results,
    direct_joint_search,
    fft_joint_search,
    process_received_waveform_to_symbols,
)
from waveform import build_preamble_reference_bank, design_front_end_filter, waveform_summary


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--iterations", type=int, default=PAPER_ITERATIONS_DETECTION)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--m1", type=int, default=DEFAULT_SEARCH_M1)
    parser.add_argument("--m2", type=int, default=DEFAULT_SEARCH_M2)
    parser.add_argument("--num-rx", type=int, default=PAPER_NUM_RX)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--mode", type=str, default=DEFAULT_SIMULATION_MODE, choices=("waveform", "fast"))
    parser.add_argument("--doppler-hz", type=float, default=PAPER_DOPPLER_HZ)
    parser.add_argument("--channel-model", type=str, default=DEFAULT_PAPER_CHANNEL_MODEL)
    parser.add_argument(
        "--threshold-calibration-iterations",
        type=int,
        default=PAPER_ITERATIONS_FALSE_ALARM,
    )
    parser.add_argument(
        "--threshold-evaluation-iterations",
        type=int,
        default=PAPER_ITERATIONS_FALSE_ALARM,
    )
    parser.add_argument(
        "--threshold-json",
        type=str,
        default=None,
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
    )
    return parser.parse_args()


def load_thresholds(path: str | Path) -> dict[int, float]:
    """Load thresholds generated by simulate_false_alarm.py."""
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    return {int(entry["L"]): float(entry["threshold"]) for entry in data["cases"]}


def threshold_file_is_usable(path: Path, args: argparse.Namespace) -> bool:
    """
    Check whether an on-disk threshold file is statistically adequate.
    """
    if not path.exists():
        return False

    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    if data.get("result_kind") != "false_alarm":
        return False

    expected_run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    if not run_configuration_matches(data, expected_run_config):
        return False

    for entry in data.get("cases", []):
        if "calibration_trials" not in entry or "evaluation_trials" not in entry:
            return False
        if int(entry["calibration_trials"]) < args.threshold_calibration_iterations:
            return False
        if int(entry["evaluation_trials"]) < args.threshold_evaluation_iterations:
            return False
    return len(data.get("cases", [])) > 0


def resolve_thresholds(args: argparse.Namespace) -> dict[int, float]:
    """
    Load thresholds from disk, or calibrate them if the file is absent or stale.
    """
    threshold_path = (
        Path(args.threshold_json)
        if args.threshold_json is not None
        else result_path(args.mode, "false_alarm_results.json")
    )
    if threshold_file_is_usable(threshold_path, args):
        return load_thresholds(threshold_path)

    print(
        f"Threshold file missing or insufficient at {threshold_path}; "
        "calibrating thresholds first."
    )
    threshold_rng = make_rng(args.seed + 1)
    run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    output = {
        "result_kind": "false_alarm",
        "mode": args.mode,
        "channel_model": args.channel_model,
        "run_config": run_config,
        "cases": [],
    }
    thresholds = {}

    for case in paper_coverage_cases():
        params = derive_parameters(case.preamble_length)
        search_grid = build_search_grid(params, M1=args.m1, M2=args.m2)
        front_end = design_front_end_filter(params)
        references = build_preamble_reference_bank(
            params=params,
            front_end=front_end,
            hopping_seed=args.seed,
        )
        result = run_false_alarm_experiment(
            params=params,
            references=references,
            search_grid=search_grid,
            snr_db=case.snr_db,
            rng=threshold_rng,
            calibration_trials=args.threshold_calibration_iterations,
            evaluation_trials=args.threshold_evaluation_iterations,
            batch_size=args.batch_size,
            num_rx=args.num_rx,
            mode=args.mode,
            front_end=front_end,
        )
        thresholds[case.preamble_length] = result["threshold"]
        output["cases"].append(
            {
                "L": case.preamble_length,
                "snr_db": case.snr_db,
                "mode": args.mode,
                "channel_model": args.channel_model,
                "threshold": result["threshold"],
                "achieved_pfa": result["achieved_pfa"],
                "target_pfa": result["target_pfa"],
                "calibration_trials": result["calibration_trials"],
                "evaluation_trials": result["evaluation_trials"],
                "calibration_statistics_mean": result["calibration_statistics_mean"],
                "calibration_statistics_std": result["calibration_statistics_std"],
                "evaluation_statistics_mean": result["evaluation_statistics_mean"],
                "evaluation_statistics_std": result["evaluation_statistics_std"],
                "calibration_pfa": result["calibration_pfa"],
                "evaluation_false_alarm_count": result["evaluation_false_alarm_count"],
            }
        )

    threshold_path.parent.mkdir(parents=True, exist_ok=True)
    with open(threshold_path, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)
    print(f"Saved calibrated thresholds to {threshold_path}")
    return thresholds


def run_validation_suite(
    params,
    search_grid,
    reference,
    front_end,
    rng,
    snr_db: float,
) -> dict:
    """
    Execute the requested validation steps on a deterministic controlled case.
    """
    validation = {}

    validation["step1_parameter_derivation"] = parameter_summary(params)

    hopping_check = validate_hopping_sequence(reference.hop_sequence, params.band_subcarriers)
    validation["step2_hopping"] = {
        "valid_indices": hopping_check["valid_indices"],
        "pattern_ok": hopping_check["pattern_ok"],
        "example_sequence": example_sequence_string(reference.hop_sequence),
    }

    validation["step3_transmitter"] = waveform_summary(
        params=params,
        waveform=reference.baseband_waveform,
        hop_sequence=reference.hop_sequence,
        front_end=front_end,
    )
    validation["step3_transmitter"]["tx_waveform_upsampled_samples"] = int(
        reference.tx_waveform_upsampled.size
    )

    validation_toa = 11.25
    validation_cfo = 10.0
    waveform_realization = apply_channel_to_waveform(
        params=params,
        tx_waveform_upsampled=reference.tx_waveform_upsampled,
        front_end=front_end,
        toa_samples=validation_toa,
        cfo_hz=validation_cfo,
        drift_hz_per_s=0.0,
        input_noise_variance=None,
        rng=rng,
        num_rx=1,
        channel_model="unit_gain",
        doppler_hz=0.0,
    )
    _, waveform_symbols = process_received_waveform_to_symbols(
        params=params,
        rx_waveform_oversampled=waveform_realization.rx_waveform_oversampled,
        front_end=front_end,
        hop_sequence=reference.hop_sequence,
    )
    fast_realization = synthesize_received_symbols_batch(
        params=params,
        hop_sequence=reference.hop_sequence,
        toa_samples=np.array([waveform_realization.true_delay_samples]),
        cfo_hz=np.array([validation_cfo]),
        drift_hz_per_s=np.array([0.0]),
        snr_db=snr_db,
        rng=rng,
        num_rx=1,
        channel_model="unit_gain",
        doppler_hz=0.0,
    )
    fast_symbols = fast_realization.clean_symbols[0]
    ratio = waveform_symbols[0] / fast_symbols[0]
    validation["step4_receiver"] = {
        "max_abs_symbol_error_waveform_vs_fast": float(
            np.max(np.abs(waveform_symbols[0] - fast_symbols[0]))
        ),
        "mean_phase_deg_waveform_vs_fast": float(np.angle(np.mean(ratio), deg=True)),
        "mean_magnitude_ratio_waveform_vs_fast": float(np.mean(np.abs(ratio))),
        "validated_true_toa_samples": float(waveform_realization.true_delay_samples),
        "validated_true_cfo_hz": validation_cfo,
    }

    direct = direct_joint_search(
        params=params,
        hop_sequence=reference.hop_sequence,
        z_symbols=waveform_symbols,
        search_grid=search_grid,
        return_surface=True,
    )
    fft_waveform = fft_joint_search(
        params=params,
        hop_sequence=reference.hop_sequence,
        z_symbols=waveform_symbols,
        search_grid=search_grid,
        return_surface=True,
    )
    fft_fast = fft_joint_search(
        params=params,
        hop_sequence=reference.hop_sequence,
        z_symbols=fast_symbols,
        search_grid=search_grid,
        return_surface=False,
    )

    validation["step5_direct_search"] = {
        "estimated_cfo_hz": direct.cfo_hz,
        "estimated_toa_samples": direct.toa_samples,
        "peak_statistic": direct.statistic,
    }
    validation["step6_fft"] = compare_search_results(direct, fft_waveform)
    validation["step6_fft"].update(
        {
            "fft_estimated_cfo_hz": fft_waveform.cfo_hz,
            "fft_estimated_toa_samples": fft_waveform.toa_samples,
            "fast_fft_estimated_cfo_hz": fft_fast.cfo_hz,
            "fast_fft_estimated_toa_samples": fft_fast.toa_samples,
            "waveform_vs_fast_fft_cfo_hz_difference": float(abs(fft_waveform.cfo_hz - fft_fast.cfo_hz)),
            "waveform_vs_fast_fft_toa_samples_difference": float(
                abs(fft_waveform.toa_samples - fft_fast.toa_samples)
            ),
        }
    )
    validation["step6_fft"]["toa_mapping_note"] = (
        "The FFT q-index is mapped through the paper's signed Eq. (6) delay "
        "formula and then wrapped into [0, Ncp) for physical-delay reporting."
    )

    return validation


def main() -> None:
    """Entry point for the detection simulation."""
    args = parse_args()
    rng = make_rng(args.seed)
    thresholds = resolve_thresholds(args)
    run_config = build_run_configuration(
        mode=args.mode,
        channel_model=args.channel_model,
        m1=args.m1,
        m2=args.m2,
        num_rx=args.num_rx,
    )
    output_path = Path(args.output) if args.output is not None else result_path(
        args.mode,
        "detection_results.json",
    )
    output = {
        "result_kind": "detection",
        "mode": args.mode,
        "channel_model": args.channel_model,
        "run_config": run_config,
        "cases": [],
    }

    for case in paper_coverage_cases():
        params = derive_parameters(case.preamble_length)
        search_grid = build_search_grid(params, M1=args.m1, M2=args.m2)
        front_end = design_front_end_filter(params)
        references = build_preamble_reference_bank(
            params=params,
            front_end=front_end,
            hopping_seed=args.seed,
        )
        validation = run_validation_suite(
            params=params,
            search_grid=search_grid,
            reference=references[0],
            front_end=front_end,
            rng=rng,
            snr_db=case.snr_db,
        )
        threshold = thresholds[case.preamble_length]
        result = run_detection_experiment(
            params=params,
            references=references,
            search_grid=search_grid,
            snr_db=case.snr_db,
            threshold=threshold,
            rng=rng,
            num_trials=args.iterations,
            batch_size=args.batch_size,
            num_rx=args.num_rx,
            channel_model=args.channel_model,
            doppler_hz=args.doppler_hz,
            mode=args.mode,
            front_end=front_end,
            collect_errors=False,
        )

        record = {
            "L": case.preamble_length,
            "snr_db": case.snr_db,
            "mode": args.mode,
            "channel_model": args.channel_model,
            "threshold": threshold,
            "validation": validation,
            "misdetection_probability": result["misdetection_probability"],
            "detection_probability": result["detection_probability"],
            "num_trials": result["num_trials"],
            "num_detected": result["num_detected"],
            "num_missed": result["num_missed"],
            "mean_statistic": result["mean_statistic"],
            "mean_abs_cfo_error_hz": result["mean_abs_cfo_error_hz"],
            "mean_abs_toa_error_us": result["mean_abs_toa_error_us"],
        }
        output["cases"].append(record)

        print(f"[Validation] L={case.preamble_length}")
        print(f"  Step 1: {validation['step1_parameter_derivation']}")
        print(f"  Step 2: {validation['step2_hopping']}")
        print(f"  Step 3: {validation['step3_transmitter']}")
        print(f"  Step 4: {validation['step4_receiver']}")
        print(f"  Step 5: {validation['step5_direct_search']}")
        print(f"  Step 6: {validation['step6_fft']}")
        print(
            f"[Detection] L={case.preamble_length:3d} "
            f"mode={args.mode:8s} "
            f"SNR={case.snr_db:6.2f} dB "
            f"Pmd={result['misdetection_probability']:.6f} "
            f"Pd={result['detection_probability']:.6f}"
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)
    print(f"Saved detection results to {output_path}")


if __name__ == "__main__":
    main()
